In [22]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

## 2. Data Collection

In [ ]:
breast_data.target

In [4]:
breast_data = load_breast_cancer()
breast_data_df = pd.DataFrame(breast_data.data,columns=breast_data.feature_names)
breast_data_df["Target"] = breast_data.target

In [5]:
breast_data_df

     mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0          17.99         10.38          122.80  ...          0.4601                  0.11890       0
1          20.57         17.77          132.90  ...          0.2750                  0.08902       0
2          19.69         21.25          130.00  ...          0.3613                  0.08758       0
3          11.42         20.38           77.58  ...          0.6638                  0.17300       0
4          20.29         14.34          135.10  ...          0.2364                  0.07678       0
..           ...           ...             ...  ...             ...                      ...     ...
564        21.56         22.39          142.00  ...          0.2060                  0.07115       0
565        20.13         28.25          131.20  ...          0.2572                  0.06637       0
566        16.60         28.08          108.30  ...          0.2218                  0.07820       0
567        20.60         29.33          140.10  ...          0.4087                  0.12400       0
568         7.76         24.54           47.92  ...          0.2871                  0.07039       1

[569 rows x 31 columns]

## 3. Data Understanding

In [6]:
breast_data_df.head()

   mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  Target
0        17.99         10.38          122.80  ...          0.4601                  0.11890       0
1        20.57         17.77          132.90  ...          0.2750                  0.08902       0
2        19.69         21.25          130.00  ...          0.3613                  0.08758       0
3        11.42         20.38           77.58  ...          0.6638                  0.17300       0
4        20.29         14.34          135.10  ...          0.2364                  0.07678       0

[5 rows x 31 columns]

In [7]:
breast_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [8]:
breast_data_df.duplicated().sum()

np.int64(0)

In [9]:
breast_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

## 4. Data Preparation

In [10]:
x = breast_data_df.drop(labels="Target",axis=1)
x

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [11]:
y = breast_data_df["Target"]
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Target, Length: 569, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=123,stratify=y)

## 5. Model Building

In [13]:
xgb_model = xgb.XGBClassifier(n_estimators=30,max_depth=3,learning_rate=0.02,gamma=1.2)

## 6. Model Training

In [14]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1.2, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.02, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=30,
              n_jobs=None, num_parallel_tree=None, ...)

## 7. Model Testing

In [15]:
y_tr_pred = xgb_model.predict(X_train)

In [16]:
y_te_pred = xgb_model.predict(X_test)

## 8. Model Evaluation

In [17]:
print(classification_report(y_train,y_tr_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96       170
           1       0.96      1.00      0.98       285

    accuracy                           0.97       455
   macro avg       0.98      0.96      0.97       455
weighted avg       0.97      0.97      0.97       455

In [18]:
confusion_matrix(y_train,y_tr_pred)

array([[157,  13],
       [  0, 285]])

In [19]:
print(classification_report(y_test,y_te_pred))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95        42
           1       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

In [20]:
confusion_matrix(y_test,y_te_pred)

array([[39,  3],
       [ 1, 71]])

## 9. Data Deployment

In [63]:
from pickle import dump

In [64]:
dump(xgb_model,open("xgb_modek.pkl","wb"))

In [68]:
from pickle import load

In [75]:
trained_model = load(open("xgb_modek.pkl",mode="rb"))

In [76]:
trained_model.predict(X_test)

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1])

In [49]:
svm_model = SVC(C=0.001,kernel='poly',gamma=0.001)

In [50]:
%%time
svm_model.fit(X_train,y_train)

CPU times: total: 9.59 s
Wall time: 9.94 s

SVC(C=0.001, gamma=0.001, kernel='poly')

In [51]:
accuracy_score(y_test,y_te_pred)

0.9649122807017544